[change&MainCharacter class] PTSD source and write class
NTUT-FUCK-PTSD/Fuck-PTSD pull request #12
Opened 2024-03-04 16:08 UTC by onon1101

2024-03-04 19:25 UTC, HeavenManySugar requested changes
ＭainCharacter不應該使用Render來處理多個GameObject，這樣在處理其他GameObject的渲染時會需要呼叫多個Render來處理

new Class的方式可能導致記憶體洩漏，請更換一種實作方式

2024-03-04 19:25 UTC, HeavenManySugar commented on src/App.cpp
> +    auto m_MainCharacter = new MainCharacter();
請不要使用new Class的方式，這可能導致記憶體洩漏
[參考資料](https://tsaiyuchi.blogspot.com/2013/05/c-new-class-or-not.html)

可以嘗試使用智慧指標unique_ptr & shared_ptr

2024-03-04 19:25 UTC, HeavenManySugar commented on src/Character/MainCharacter.cpp
> +    auto HeadImage = std::make_shared<SpriteSheet>(
Hard code

2024-03-04 19:25 UTC, HeavenManySugar commented on src/Character/MainCharacter.cpp
> +    auto BodyImage =
Hard code

2024-03-04 19:25 UTC, HeavenManySugar commented on include/Character/MainCharacter.h
> +    void Render(Util::Root &m_Render);
我覺得這裡不應該用Render來處理，使用GameObject中的draw和children的方式就可以完成的更好了

2024-03-05 03:04 UTC, onon1101 commented on include/Character/MainCharacter.h
> +    void Render(Util::Root &m_Render);
所以你想要的是這嗎

```suggestion
    Util::GameObject GetRender () { return m_MainCharacter} ;
```

然後這樣引用
```cpp

# App.cpp
auto test = MainCharacter::GetRender();
m_Root.AddChild(test);
```

但這樣會報錯, 在PTSD裡面他只是一個抽象類別
<img width="1470" alt="image" src="https://github.com/NTUT-FUCK-PTSD/Fuck-PTSD/assets/98307453/e1fee34e-f98e-4393-878c-87c66e286743">

2024-03-05 03:06 UTC, HeavenManySugar commented on include/Character/MainCharacter.h
> +    void Render(Util::Root &m_Render);
他並不是抽象類別喔，這裡的錯誤是因為他downcast了

2024-03-05 03:09 UTC, HeavenManySugar commented
Util/Root.hpp應該被Util/Renderer.hpp取代

2024-03-05 03:14 UTC, HeavenManySugar commented on include/Character/MainCharacter.h
> +    void Render(Util::Root &m_Render);
我的想法是GameObject元素不應該擁有Renderer，並且Renderer的Children資料型別應該為GameObject，而非Renderer

2024-03-05 03:19 UTC, HeavenManySugar commented on include/Character/MainCharacter.h
> +    void Render(Util::Root &m_Render);
![image](https://github.com/NTUT-FUCK-PTSD/Fuck-PTSD/assets/25154413/75b185ec-4293-4bfd-9c9b-e409aac79f87)
這是我之前的一些想法，大致應該是這樣，看看有沒有哪裡不妥

2024-03-05 03:20 UTC, HeavenManySugar commented on include/Character/MainCharacter.h
> +    void Render(Util::Root &m_Render);
m_Protagonist_Head可能有誤導的意思，這個名字可能需要注意一下，此Head非彼Head

2024-03-05 05:02 UTC, HeavenManySugar approved these changes

2024-03-05 05:10 UTC, merged